#
# compose.yaml - PYPONG Docker Development Environment
#
# 5 services: nginx + Flask + Django + FastAPI + postgresql
#
services:

    db:
        build:
            context: ./database/
            dockerfile: Dockerfile

        image: postgresql-image
        container_name: pypong-postgresql-container

        networks:
            - pypong-network

        ports:
            - "5432"

        env_file:
            - .env

        volumes:
            - pypong-data:/var/lib/postgresql/data

        restart: unless-stopped

    flask:
        build:
            context: ./src/flask/
            dockerfile: ../../python/Dockerfile

        image: flask-image
        container_name: pypong-flask-container

        networks:
            - pypong-network

        ports:
            - "8000"

        working_dir: /var/www

        env_file:
            - .env

        environment:
            - POSTGRES_HOST=pypong-postgresql-container
            - POSTGRES_PORT=5432
            - PGPORT=5432

        depends_on:
            - db

        restart: unless-stopped

    django:
        build:
            context: ./src/django/
            dockerfile: ../../python/django.Dockerfile

        image: django-image
        container_name: pypong-django-container

        networks:
            - pypong-network

        ports:
            - "8001"

        working_dir: /var/www

        env_file:
            - .env

        environment:
            - POSTGRES_HOST=pypong-postgresql-container
            - POSTGRES_PORT=5432
            - PGPORT=5432

        depends_on:
            - db

        restart: unless-stopped

    fastapi:
        build:
            context: ./src/fastapi/
            dockerfile: ../../python/fastapi.Dockerfile

        image: fastapi-image
        container_name: pypong-fastapi-container

        networks:
            - pypong-network

        ports:
            - "8002"

        working_dir: /var/www

        env_file:
            - .env

        environment:
            - POSTGRES_HOST=pypong-postgresql-container
            - POSTGRES_PORT=5432
            - PGPORT=5432

        depends_on:
            - db

        restart: unless-stopped

    webserver:
        build:
            context: ./webserver/
            dockerfile: Dockerfile

        image: nginx-image
        container_name: pypong-nginx-container

        networks:
            - pypong-network

        ports:
            - "127.0.0.1:8080:8080"

        volumes:
            - ./src:/var/www/html:ro

        depends_on:
            - flask
            - django
            - fastapi

        restart: unless-stopped

networks:

    pypong-network:
        driver: bridge

volumes:

    pypong-data: